Now with better error handling

diff --git a/pipelines/03_rgclone-refresh-di.yaml b/pipelines/03_rgclone-refresh-di.yaml
--- a/pipelines/03_rgclone-refresh-di.yaml
+++ b/pipelines/03_rgclone-refresh-di.yaml
@@ -21,24 +21,56 @@ stages:
 
       steps:
       - powershell: |
+          $ErrorActionPreference = 'Stop'
           # Authenticating against cloning cluster
-          Write-Output "Authenticating against the cloning cluster with token $env:RGCLONE_ACCESS_TOKEN"
+          Write-Output "Authenticating against the cloning cluster"
           rgclone auth -t $env:RGCLONE_ACCESS_TOKEN
+          if ($lastExitCode -ne 0){
+            echo "##vso[task.logissue type=error]Failed to authenticate against cloning cluster"
+            exit 1
+          }
 
-          # Set any old images to lifetime of 1m (fast delete)
-          Write-Output "If exists, renaming empty-sql-old image to empty-sql-deleting, and setting lifetime to 1m"
-          rgclone update di empty-sql-old -n empty-sql-deleting
-          rgclone update di empty-sql-deleting -t 1m
+          # Reducing duplication with vars
+          $imageName = "empty-sql"
+          $oldName = "$imageName-old"
+          $deletingName = "$imageName-deleting"
+          $newName = "$imageName-new"
+          $currentName = "$imageName-current"
+
+          # Set any old image to lifetime of 1m (fast delete)
+          Write-Output "If exists, renaming $oldName image to $deletingName, and setting lifetime to 1m"
+          rgclone update di $oldName -n $deletingName
+          if ($lastExitCode -eq 0){
+            rgclone update di $deletingName -t 1m
+            if ($lastExitCode -ne 0){
+              echo "##vso[task.logissue type=error]No image found called $deletingName"
+              exit 1
+            }
+          }
+          else {
+            echo "##vso[task.logissue type=warning]No image found called $oldName"
+          }
 
           # Create a new data image
-          Write-Output "Creating new data image, with name empty-sql-new"
-          rgclone create di -f config\empty-sql.yaml -n empty-sql-new
+          Write-Output "Creating new data image, with name $newName"
+          rgclone create di -f config\empty-sql.yaml -n $newName
+          if ($lastExitCode -ne 0){
+            echo "##vso[task.logissue type=error]Failed to create image with name $newName"
+            exit 1
+          }
 
           # Name swap (near zero downtime)
-          Write-Output "Name swapping empty-sql-current > empty-sql-old"
-          rgclone update di empty-sql-current -n empty-sql-old
-          Write-Output "Name swapping empty-sql-new > empty-sql-current"
-          rgclone update di empty-sql-new -n empty-sql-current
+          Write-Output "Name swapping $currentName > $oldName"
+          rgclone update di $currentName -n $oldName
+          if ($lastExitCode -ne 0){
+            echo "##vso[task.logissue type=warning]No image found called $oldName"
+          }
+          Write-Output "Name swapping $newName > $currentName"
+          rgclone update di $newName -n $currentName
+          if ($lastExitCode -ne 0){
+            echo "##vso[task.logissue type=error]Failed to create image with name $newName"
+            exit 1
+          } 
         env:
           RGCLONE_ACCESS_TOKEN: $(RGCLONE_ACCESS_TOKEN)
         displayName: 'Refresh rgclone data image'
